// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: notification.proto

package notification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	NotificationService_SendMailConfirmLink_FullMethodName = "/notification.NotificationService/SendMailConfirmLink"
	NotificationService_MailConfirmation_FullMethodName    = "/notification.NotificationService/MailConfirmation"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	SendMailConfirmLink(ctx context.Context, in *SendMailConfirmLinkRequest, opts ...grpc.CallOption) (*SendMailConfirmLinkResponse, error)
	MailConfirmation(ctx context.Context, in *MailConfirmationRequest, opts ...grpc.CallOption) (*MailConfirmationResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) SendMailConfirmLink(ctx context.Context, in *SendMailConfirmLinkRequest, opts ...grpc.CallOption) (*SendMailConfirmLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMailConfirmLinkResponse)
	err := c.cc.Invoke(ctx, NotificationService_SendMailConfirmLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) MailConfirmation(ctx context.Context, in *MailConfirmationRequest, opts ...grpc.CallOption) (*MailConfirmationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MailConfirmationResponse)
	err := c.cc.Invoke(ctx, NotificationService_MailConfirmation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility
type NotificationServiceServer interface {
	SendMailConfirmLink(context.Context, *SendMailConfirmLinkRequest) (*SendMailConfirmLinkResponse, error)
	MailConfirmation(context.Context, *MailConfirmationRequest) (*MailConfirmationResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (UnimplementedNotificationServiceServer) SendMailConfirmLink(context.Context, *SendMailConfirmLinkRequest) (*SendMailConfirmLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMailConfirmLink not implemented")
}
func (UnimplementedNotificationServiceServer) MailConfirmation(context.Context, *MailConfirmationRequest) (*MailConfirmationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MailConfirmation not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_SendMailConfirmLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMailConfirmLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendMailConfirmLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendMailConfirmLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendMailConfirmLink(ctx, req.(*SendMailConfirmLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_MailConfirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).MailConfirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_MailConfirmation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).MailConfirmation(ctx, req.(*MailConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMailConfirmLink",
			Handler:    _NotificationService_SendMailConfirmLink_Handler,
		},
		{
			MethodName: "MailConfirmation",
			Handler:    _NotificationService_MailConfirmation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
