port: 8000

api:
  url: "http://0.0.0.0:82/api/"

auth:
  hash_salt: "business universe"
  signing_key: "3430bc4181f10c5c023d1c99fea55e26d3fa8f7a"
  token_exp: 60


postgres:
  uri: "host=b24-db user=postgres password=2yZnWGfq8G dbname=postgres port=5432 sslmode=disable"
  uri_local: "host=localhost user= password= dbname=postgres port=5432 sslmode=disable"

grpc:
  user:
    port: "9001"
    host: "b24-user-grpc"
  notification:
    port: "9002"
    host: "b24-notification-grpc"

http:
  user:
    port: "8091"
    host: "b24-user-http"

mail:
  auth:
    user: "@gmail.com"
    password: ""
    host: "smtp.gmail.com"
    port: "587"